name: Build
on:
  push:
  
jobs:
  tag:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build
